-- Codiguera de Eventos
INSERT INTO eventos(id, nombre, comentario) VALUES (1, 'LESION', null);
INSERT INTO eventos(id, nombre, comentario) VALUES (2, 'JUGADA_GOL', null);
INSERT INTO eventos(id, nombre, comentario) VALUES (3, 'GOL', 'Goooool de %s para %s |%s $d x $d $s |');
INSERT INTO eventos(id, nombre, comentario) VALUES (4, 'TARJETA_AMARILLA', 'Tarjeta amarilla para el jugador %s');
INSERT INTO eventos(id, nombre, comentario) VALUES (5, 'TARJETA_AMARILLA_DOBLE', 'Tarjeta amarilla para el jugador %s, esta es la segunda y se va');
INSERT INTO eventos(id, nombre, comentario) VALUES (6, 'TARJETA_ROJA', 'Groseeero %s, expulsión directa');
INSERT INTO eventos(id, nombre, comentario) VALUES (7, 'FALTA', 'Falta cometida sobre el jugador %s');
INSERT INTO eventos(id, nombre, comentario) VALUES (8, 'INICIO_PARTIDO', 'Comienza el partido');
INSERT INTO eventos(id, nombre, comentario) VALUES (9, 'FIN_PRIMER_TIEMPO', 'Finaliza el primer tiempo');
INSERT INTO eventos(id, nombre, comentario) VALUES (10,'INICIO_SEGUNDO_TIEMPO', 'Se inicia el segundo tiempo');
INSERT INTO eventos(id, nombre, comentario) VALUES (11, 'FIN_PARTIDO', 'Ha finalizado el partido');

-- Codiguera de comentarios
INSERT INTO comentarios(id, evento_id, descripcion, nivel) VALUES (1,2,'%s escapa por la punta, centro al segundo palo, entran varios!', 1);
INSERT INTO comentarios(id, evento_id, descripcion, nivel) VALUES (2,2,'%s levanta el corner, centro al medio, puede venir!', 2);
INSERT INTO comentarios(id, evento_id, descripcion, nivel) VALUES (3,2,'Entra al area el jugador %s, burla a 1 defensa, 2, 3 remataaaa', 3);
INSERT INTO comentarios(id, evento_id, descripcion, nivel) VALUES (4,7,'Falta cometida sobre el jugador %s', 1);
INSERT INTO comentarios(id, evento_id, descripcion, nivel) VALUES (5,7,'Falta sobre el jugador %s. El cuerpo medico esta en campo pero el jugador se recupera', 2);
INSERT INTO comentarios(id, evento_id, descripcion, nivel) VALUES (6,7,'Grosera falta sobre el jugador %s, el cual es retirado del campo de juego', 3);



-- Codiguera de Datos Jugadores

insert into datos_jugador values (1,'C.Mendoza ');
insert into datos_jugador values (2,'A.González ');
insert into datos_jugador values (3,'D.Araújo ');
insert into datos_jugador values (4,'P.Mares ');
insert into datos_jugador values (5,'A.Geijer ');
insert into datos_jugador values (6,'R.Costa ');
insert into datos_jugador values (7,'E.Gil ');
insert into datos_jugador values (8,'J.Ferér ');
insert into datos_jugador values (9,'V.Alvarenga ');
insert into datos_jugador values (10,'A.Åsberg ');
insert into datos_jugador values (11,'M.Key ');
insert into datos_jugador values (12,'R.Gjersell ');
insert into datos_jugador values (13,'T.Rebari ');
insert into datos_jugador values (14,'N.Donato ');
insert into datos_jugador values (15,'R.Dalmonte ');
insert into datos_jugador values (16,'D.Furacão ');
insert into datos_jugador values (17,'G.Edu ');
insert into datos_jugador values (18,'M.Holetz ');
insert into datos_jugador values (19,'Z.Andrade ');
insert into datos_jugador values (20,'A.Marinho ');
insert into datos_jugador values (21,'D.Cardozo ');
insert into datos_jugador values (22,'T.Irrureta ');
insert into datos_jugador values (23,'O.Meilton ');
insert into datos_jugador values (24,'M.Martínez ');
insert into datos_jugador values (25,'J.Scheinhardt ');
insert into datos_jugador values (26,'T.Cadete ');
insert into datos_jugador values (27,'R.Brindisi ');
insert into datos_jugador values (28,'J.Artoni ');
insert into datos_jugador values (29,'M.Cufré ');
insert into datos_jugador values (30,'F.Perez ');
insert into datos_jugador values (31,'S.Batistuta ');
insert into datos_jugador values (32,'R.Oliveria ');
insert into datos_jugador values (33,'D.Cardozo ');
insert into datos_jugador values (34,'E.Losaldo ');
insert into datos_jugador values (35,'G.Melfi ');
insert into datos_jugador values (36,'P.Franco ');
insert into datos_jugador values (37,'L.Krauss ');
insert into datos_jugador values (38,'R.Recoba ');
insert into datos_jugador values (39,'J.Guardiola ');
insert into datos_jugador values (40,'G.Giusti ');
insert into datos_jugador values (41,'S.Galdames ');
insert into datos_jugador values (42,'V.Junior ');
insert into datos_jugador values (43,'A,Sabas ');
insert into datos_jugador values (44,'M.Manjarin ');
insert into datos_jugador values (45,'E.Enrique ');
insert into datos_jugador values (46,'C.Norris ');
insert into datos_jugador values (47,'O.Ato ');
insert into datos_jugador values (48,'O.Lembowski ');
insert into datos_jugador values (49,'G.Torre ');
insert into datos_jugador values (50,'E.Dunga ');
insert into datos_jugador values (51,'C.Aizpurua ');
insert into datos_jugador values (52,'A.Castro ');
insert into datos_jugador values (53,'J.Ribera ');
insert into datos_jugador values (54,'H.Ilhan ');
insert into datos_jugador values (55,'M.Tinoco ');
insert into datos_jugador values (56,'I.Virgílio ');
insert into datos_jugador values (57,'A.Boroja ');
insert into datos_jugador values (58,'P.Bengoechea ');
insert into datos_jugador values (59,'F.Beckenbauer ');
insert into datos_jugador values (60,'M.Veloso ');
insert into datos_jugador values (61,'A.Maldonado ');
insert into datos_jugador values (62,'S.Amessi ');
insert into datos_jugador values (63,'M.Losaldo ');
insert into datos_jugador values (64,'D.Curle ');
insert into datos_jugador values (65,'W.Pandiani ');
insert into datos_jugador values (66,'I.Braco ');
insert into datos_jugador values (67,'H.Schelin ');
insert into datos_jugador values (68,'L.Alessandro ');
insert into datos_jugador values (69,'R.Dorronsoro ');
insert into datos_jugador values (70,'R.Cesaretti ');
insert into datos_jugador values (71,'L.Misco ');
insert into datos_jugador values (72,'F.Sorondo ');
insert into datos_jugador values (73,'J.Poutiainen ');
insert into datos_jugador values (74,'D.Carini ');
insert into datos_jugador values (75,'I.Diogo ');
insert into datos_jugador values (76,'F.Rosa ');
insert into datos_jugador values (77,'M.Fúriga ');
insert into datos_jugador values (78,'H.Mortensen ');
insert into datos_jugador values (79,'R.Biriotti ');
insert into datos_jugador values (80,'S.Kralj ');
insert into datos_jugador values (81,'M.Memic ');
insert into datos_jugador values (82,'V.Radosevic ');
insert into datos_jugador values (83,'D.Foric ');
insert into datos_jugador values (84,'M.Wietono ');
insert into datos_jugador values (85,'C.Dudic ');
insert into datos_jugador values (86,'N.Cirkovic ');
insert into datos_jugador values (87,'R.Horacio ');
insert into datos_jugador values (88,'E.Hermansson ');
insert into datos_jugador values (89,'Z.Talic ');
insert into datos_jugador values (90,'S.Björkman ');
insert into datos_jugador values (91,'J.Artigas ');
insert into datos_jugador values (92,'L.Garcia ');
insert into datos_jugador values (93,'H.Troche ');
insert into datos_jugador values (94,'S.Alejnikov ');
insert into datos_jugador values (95,'P.Filgueira ');
insert into datos_jugador values (96,'M.Echeverria ');
insert into datos_jugador values (97,'Z.Hadzibegic ');
insert into datos_jugador values (98,'I.Villasboas ');
insert into datos_jugador values (99,'P.Carvalho ');
insert into datos_jugador values (100,'R.Gaucho ');